export const style = {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%) !important",
    // width: 400,
    bgcolor: "white",
    // border: "2px solid #000",
    boxShadow: 24,
    outline: "none",
    p: 4, 
    overflowY: "auto",
    height: "475px",
    // width: "583px",
  };